---
- name: add bastion to ssh config
  local_action:
    module: ssh_config
    user: "{{ lookup('env', 'USER') }}"
    remote_user: ec2-user
    host: "bastion.{{ public_hosted_zone }}"
    identity_file: "{{ key_path }}"
    proxycommand: "none"
    strict_host_key_checking: no
    state: present
  # see https://github.com/gaqzi/ansible-ssh-config/issues/22
  ignore_errors: yes
  become: no

- name: add proxy to ssh config
  local_action:
    module: ssh_config
    user: "{{ lookup('env', 'USER') }}"
    remote_user: ec2-user
    host: "*.{{ public_hosted_zone }}"
    identity_file: "{{ key_path }}"
    proxycommand: "ssh ec2-user@bastion.{{ public_hosted_zone }} -W %h:%p"
    state: present
  # see https://github.com/gaqzi/ansible-ssh-config/issues/22
  ignore_errors: yes
  become: no

- name: check to see if host is available
  wait_for:
    port: 22
    host: "bastion.{{ public_hosted_zone }}"
    state: started
    delay: "{{ host_up_time }}"
  when: byo_bastion == "no"
